### ISSUE TITLE
Removal Candidate

### ISSUE THREAD

**Issue by Adurol** [KaOS-Community-Packages/python2-scipy#1]
This Package will be removed in 7 days from KCP.

Reason: **Unmaintained**
Missing dependencies

Please see also: [Using KaOS Community Packages](https://kaosx.us/phpBB3/viewtopic.php?f=12&t=145) and [KCP Guide](https://kaosx.us/kcp-guide/)

**Comment by demmm** [comment]
Make sure to check depends by building, both distribute & gcc-fortran are correct, they will pull the needed packages from the repo, that is why when renaming/different splits occur, "provides" lines are added.  Example, see the provides line in ```pacman -Sii python2=setuptools```
Just being outdated is not a reason to remove.
